export const quiz = {
  totalQuestions: 24,
  questions: [
    {
      id: 1,
      question: "In which of the following changes, the nitrogen atom is reduced?",
      answers: [
        "N₂ to NO",
        "N₂ to NO₂",
        "N₂ to NH₃",
        "N₂ to HNO₃",
      ],
      correctAnswer: "N₂ to NH₃",
    },
    {
      id: 2,
      question: "Which of the following changes reaction is an example of oxidation?",
      answers: [
        "Chlorine molecule to chloride ion",
        "Silver atoms to silver (I) ion",
        "Oxygen molecule to oxide ion",
        "Iron (III) ion to iron (II) ion",
      ],
      correctAnswer: "Silver atoms to silver (I) ion",
    },
    {
      id: 3,
      question: "Which of the following elements in the given reaction is reduced? ZnO + H₂ → Zn + H₂O",
      answers: ["H₂", "ZnO", "Zn", "O"],
      correctAnswer: "ZnO",
    },
    {
      id: 4,
      question: "Consider the following reaction: H₂S + Cl₂ → 2HCl + S. In this reaction, H₂S behaves as:",
      answers: [
        "Reducing agent",
        "Catalyst",
        "Oxidizing agent",
        "Electrolyte",
      ],
      correctAnswer: "Reducing agent",
    },
    {
      id: 5,
      question: "The oxidation state of Cr in K₂Cr₂O₇ is:",
      answers: ["+12", "+6", "+3", "-6"],
      correctAnswer: "+6",
    },
    {
      id: 6,
      question: "In the reaction Fe + CuSO₄ → FeSO₄ + Cu, which species undergoes reduction?",
      answers: ["Fe", "Cu", "SO₄²⁻", "FeSO₄"],
      correctAnswer: "Cu",
    },
    {
      id: 7,
      question: "Identify the oxidizing agent in the reaction: 2SO₂ + O₂ → 2SO₃",
      answers: ["SO₂", "O₂", "Both SO₂ and O₂", "None of these"],
      correctAnswer: "O₂",
    },
    {
      id: 8,
      question: "Determine the oxidation number of chromium in Cr₂O₃.",
      answers: ["+6", "+3", "-2", "0"],
      correctAnswer: "+3",
    },
    {
      id: 9,
      question: "Considering the reaction: Cl₂ + 2Na → 2NaCl, what is the change in oxidation number of chlorine?",
      answers: ["0 to +1", "0 to -1", "+1 to 0", "-1 to 0"],
      correctAnswer: "0 to -1",
    },
    {
      id: 10,
      question: "Predict the formula of the ionic compound formed between calcium (Ca²⁺) and phosphate (PO₄³⁻).",
      answers: ["CaPO₄", "Ca₂PO₄", "Ca₃(PO₄)₂", "Ca(PO₄)₂"],
      correctAnswer: "Ca₃(PO₄)₂",
    },
    {
      id: 11,
      question: "Which statement about oxidation number is incorrect?",
      answers: [
        "The oxidation number of an element in its free state is zero.",
        "The sum of oxidation numbers in a neutral molecule is zero.",
        "The oxidation number of a monatomic ion is equal to its charge.",
        "The oxidation number of oxygen in most compounds is -2.",
      ],
      correctAnswer: "The oxidation number of oxygen in most compounds is -2.",
    },
    {
      id: 12,
      question: "In the balanced equation: PbO₂ + 4CO → Pb + 4CO₂, what is the role of carbon monoxide (CO)?",
      answers: [
        "Oxidizing agent",
        "Reducing agent",
        "Neither oxidizing nor reducing agent",
        "Both of these",
      ],
      correctAnswer: "Reducing agent",
    },
    {
      id: 13,
      question: "Analyze the reaction: MnO₂ + 4HCl → MnCl₂ + 2H₂O + Cl₂. Identify the element undergoing the largest increase in oxidation number.",
      answers: ["Mn", "H", "Cl", "O"],
      correctAnswer: "Cl",
    },
    {
      id: 14,
      question: "Which of the following statements about the oxidation number of elements in their free state is correct?",
      answers: [
        "It is always positive",
        "It is always negative",
        "It is always zero",
        "It varies depending on the element.",
      ],
      correctAnswer: "It is always zero",
    },
    {
      id: 15,
      question: "How is the formula of an ionic compound derived from ionic charges and oxidation numbers?",
      answers: [
        "By taking the average of the charges",
        "By multiplying the charges",
        "By finding the common multiples of the charges",
        "By balancing the charges to achieve a neutral compound.",
      ],
      correctAnswer: "By balancing the charges to achieve a neutral compound.",
    },
    {
      id: 16,
      question: "What does the oxidation number of a monatomic ion represent?",
      answers: [
        "The number of protons",
        "The number of neutrons",
        "The charge on the ion",
        "The number of electrons gained",
      ],
      correctAnswer: "The charge on the ion",
    },
    {
      id: 17,
      question: "Recognize that the sum of oxidation numbers in a neutral compound is:",
      answers: [
        "Always positive",
        "Always negative",
        "Zero",
        "Equal to the number of atoms present",
      ],
      correctAnswer: "Zero",
    },
  ],
};