export const quiz = {
  totalQuestions: 20,
  questions: [
    {
      id: 1,
      question: "What is the SI unit of force?",
      answers: ["Newton (N)", "Kilogram (kg)", "Meter (m)", "Second (s)"],
      correctAnswer: "Newton (N)",
    },
    {
      id: 2,
      question: "Which of Newton&apos;slaws of motion describes the relationship between force, mass, and acceleration?",
      answers: ["First law", "Second law", "Third law", "None of the above"],
      correctAnswer: "Second law",
    },
    {
      id: 3,
      question: "What is the formula for the net force acting on a body?",
      answers: ["F = ma", "F = kx", "F = μN", "F = Σ Fi"],
      correctAnswer: "F = Σ Fi",
    },
    {
      id: 4,
      question: "What is the purpose of determining the line of action of a force?",
      answers: ["To calculate the magnitude of the force", "To determine the direction of the force", "To find the net force acting on the body", "To understand the effect of the force on the body"],
      correctAnswer: "To understand the effect of the force on the body",
    },
    {
      id: 5,
      question: "What is the definition of parallel forces?",
      answers: ["Forces that act in the same direction", "Forces that act in opposite directions", "Forces that intersect at a point", "Forces that are perpendicular to each other"],
      correctAnswer: "Forces that act in the same direction",
    },
    {
      id: 6,
      question: "What is the difference between 'like parallel forces' and 'unlike parallel forces'?",
      answers: ["Like parallel forces act in the same direction, unlike parallel forces act in opposite directions", "Like parallel forces act in opposite directions, unlike parallel forces act in the same direction", "Like parallel forces intersect at a point, unlike parallel forces are perpendicular to each other", "There is no difference between like parallel forces and unlike parallel forces"],
      correctAnswer: "Like parallel forces act in the same direction, unlike parallel forces act in opposite directions",
    },
    {
      id: 7,
      question: "What is the role of the center of mass in the stability of a body?",
      answers: ["It determines the rotational stability of the body", "It determines the translational stability of the body", "It determines the overall stability of the body", "It has no effect on the stability of the body"],
      correctAnswer: "It determines the overall stability of the body",
    },
    {
      id: 8,
      question: "What is the effect of a force that acts perpendicular to the line of motion of a body?",
      answers: ["It causes the body to accelerate", "It causes the body to decelerate", "It causes the body to rotate", "It has no effect on the body"],
      correctAnswer: "It causes the body to rotate",
    },
    {
      id: 9,
      question: "What is the relationship between the magnitude of a force and the angle between the force and the displacement of a body?",
      answers: ["The force and the displacement are directly proportional", "The force and the displacement are inversely proportional", "The force and the displacement are related by the cosine of the angle between them", "There is no relationship between the force and the displacement"],
      correctAnswer: "The force and the displacement are related by the cosine of the angle between them",
    },
    {
      id: 10,
      question: "What is the formula for the work done by a force?",
      answers: ["W = Fd", "W = F/d", "W = F × d × cos(θ)", "W = F × d"],
      correctAnswer: "W = F × d × cos(θ)",
    },
    {
      id: 11,
      question: "What is the relationship between the work done by a force and the change in kinetic energy of a body?",
      answers: ["Work done is equal to the change in kinetic energy", "Work done is greater than the change in kinetic energy", "Work done is less than the change in kinetic energy", "There is no relationship between work done and change in kinetic energy"],
      correctAnswer: "Work done is equal to the change in kinetic energy",
    },
    {
      id: 12,
      question: "What is the formula for the torque acting on a body?",
      answers: ["τ = r × F", "τ = F/r", "τ = F × r × cos(θ)", "τ = F × r"],
      correctAnswer: "τ = r × F",
    },
    {
      id: 13,
      question: "What is the effect of torque on the rotational motion of a body?",
      answers: ["Torque causes the body to accelerate", "Torque causes the body to decelerate", "Torque causes the body to rotate", "Torque has no effect on the rotational motion of the body"],
      correctAnswer: "Torque causes the body to rotate",
    },
    {
      id: 14,
      question: "What is the formula for the angular acceleration of a body?",
      answers: ["α = τ/I", "α = ω/t", "α = ΣMi/I", "α = Σr × Fi/I"],
      correctAnswer: "α = Σr × Fi/I",
    },
    {
      id: 15,
      question: "What is the relationship between the angular acceleration and the angular velocity of a body?",
      answers: ["Angular acceleration is directly proportional to angular velocity", "Angular acceleration is inversely proportional to angular velocity", "Angular acceleration is related to the square of angular velocity", "There is no relationship between angular acceleration and angular velocity"],
      correctAnswer: "Angular acceleration is directly proportional to angular velocity",
    },
    {
      id: 16,
      question: "What is the definition of the center of mass of a body?",
      answers: ["The point where the entire mass of the body is concentrated", "The point where the body balances on a pivot", "The point where the body experiences the maximum gravitational force", "The point where the body experiences the minimum gravitational force"],
      correctAnswer: "The point where the entire mass of the body is concentrated",
    },
    {
      id: 17,
      question: "What is the relationship between the center of mass and the center of gravity of a body?",
      answers: ["They are always the same point", "They are always different points", "The center of mass is above the center of gravity", "The center of mass is below the center of gravity"],
      correctAnswer: "They are always the same point",
    },
    {
      id: 18,
      question: "What is the effect of the position of the center of mass on the stability of a body?",
      answers: ["A higher center of mass increases stability", "A lower center of mass increases stability", "The position of the center of mass has no effect on stability", "Stability depends on both the position of the center of mass and the center of gravity"],
      correctAnswer: "A lower center of mass increases stability",
    },
    {
      id: 19,
      question: "What is the difference between static and dynamic equilibrium?",
      answers: ["Static equilibrium involves no motion, dynamic equilibrium involves constant motion", "Static equilibrium involves constant motion, dynamic equilibrium involves no motion", "Static equilibrium involves the net force being zero, dynamic equilibrium involves the net torque being zero", "There is no difference between static and dynamic equilibrium"],
      correctAnswer: "Static equilibrium involves the net force being zero, dynamic equilibrium involves the net torque being zero",
    },
    {
      id: 20,
      question: "What is the condition for a body to be in stable equilibrium?",
      answers: ["The center of mass must be above the point of support", "The center of mass must be below the point of support", "The center of mass must be directly above the point of support", "The center of mass can be in any position relative to the point of support"],
      correctAnswer: "The center of mass must be below the point of support",
    },
  ],
};