export const quiz = {
  totalQuestions: 18,
  questions: [
    {
      id: 1,
      question: "Which is true about the equilibrium state?",
      answers: [
        "a) The forward reaction stops",
        "b) The reverse reaction stops",
        "c) Both forward and reverse reaction stops.",
        "d) Both forward and reverse reactions continue at the same rate.",
      ],
      correctAnswer: "d) Both forward and reverse reactions continue at the same rate.",
    },
    {
      id: 2,
      question: "When a mixture of H2 and I2 is sealed in a flask and temperature is kept at 25°C, following equilibrium is established. H2(g) + I2(g) ⇌ 2HI(g). Which substance or substances will be present in the equilibrium mixture?",
      answers: [
        "a) H₂ and I₂",
        "b) HI only",
        "c) H₂ only",
        "d) H2, I2, and HI",
      ],
      correctAnswer: "d) H2, I2, and HI",
    },
    {
      id: 3,
      question: "Concentration of reactants and products at equilibrium remains unchanged if",
      answers: [
        "a) Concentration of any reactant or product is not changed",
        "b) temperature of the reaction is not changed",
        "c) pressure or volume of the system is not changed",
        "d) all of the above are observed.",
      ],
      correctAnswer: "d) all of the above are observed.",
    },
    {
      id: 4,
      question: "Which of the following does not happen, when a system is at equilibrium state?",
      answers: [
        "a) forward and reverse reactions stop.",
        "b) forward and reverse rates become equal",
        "c) concentration of reactants and products stop changing",
        "d) reaction continues to occur in both the directions",
      ],
      correctAnswer: "a) forward and reverse reactions stop.",
    },
    {
      id: 5,
      question: "In a reversible reaction equilibrium is",
      answers: [
        "a) established quickly",
        "b) established slowly",
        "c) never established",
        "d) established when reaction stops",
      ],
      correctAnswer: "c) never established",
    },
    {
      id: 6,
      question: "What symbol represents a reversible reaction?",
      answers: [
        "a) →",
        "b) ⇌",
        "c) ←",
        "d) Ů",
      ],
      correctAnswer: "b) ⇌",
    },
    {
      id: 7,
      question: "In a closed system at dynamic equilibrium, what happens to the rate of the forward and reverse reactions?",
      answers: [
        "a) The forward reaction rate is higher",
        "b) The reverse reaction rate is higher",
        "c) Both rates are equal.",
        "d) Both reactions stop",
      ],
      correctAnswer: "c) Both rates are equal.",
    },
    {
      id: 8,
      question: "Le Chatelier's Principle states that a system at equilibrium will:",
      answers: [
        "a) Stay unchanged when conditions are altered.",
        "b) Shift to increase stress.",
        "c) Shift to reduce stress.",
        "d) Always favor the forward reaction.",
      ],
      correctAnswer: "c) Shift to reduce stress.",
    },
    {
      id: 9,
      question: "What happens to the concentration of reactants and products at chemical equilibrium?",
      answers: [
        "a) They continue changing.",
        "b) They become zero.",
        "c) They remain constant.",
        "d) Only reactants remain.",
      ],
      correctAnswer: "c) They remain constant.",
    },
    {
      id: 10,
      question: "In the context of dynamic equilibrium, what is true about the reaction rates?",
      answers: [
        "a) Only the forward reaction occurs.",
        "b) Only the reverse reaction occurs.",
        "c) Both reactions occur at different rates.",
        "d) Both reactions occur at the same rate.",
      ],
      correctAnswer: "d) Both reactions occur at the same rate.",
    },
    {
      id: 11,
      question: "Adding more reactant to a system at equilibrium will:",
      answers: [
        "a) Decrease product formation.",
        "b) Have no effect on the system.",
        "c) Increase product formation.",
        "d) Stop the reaction",
      ],
      correctAnswer: "c) Increase product formation.",
    },
    {
      id: 12,
      question: "How does an increase in temperature affect an exothermic reaction at equilibrium?",
      answers: [
        "a) Shifts towards reactants.",
        "b) Shifts towards products.",
        "c) Stops the reaction.",
        "d) Has no effect.",
      ],
      correctAnswer: "a) Shifts towards reactants.",
    },
    {
      id: 13,
      question: "What is a characteristic feature of dynamic equilibrium in a chemical reaction?",
      answers: [
        "a) Reaction occurs in one direction only.",
        "b) Concentration of reactants and products is dynamic.",
        "c) The concentration of reactants and products is static.",
        "d) No reactions occur.",
      ],
      correctAnswer: "b) Concentration of reactants and products is dynamic.",
    },
    {
      id: 14,
      question: "What happens when a product is removed from a reaction at equilibrium?",
      answers: [
        "a) The forward reaction is favored.",
        "b) The reverse reaction is favored.",
        "c) The reaction stops.",
        "d) There is no change in the reaction",
      ],
      correctAnswer: "a) The forward reaction is favored.",
    },
    {
      id: 15,
      question: "What does the addition of a catalyst do to a system at equilibrium?",
      answers: [
        "a) Changes the equilibrium position.",
        "b) Favors the forward reaction.",
        "c) Favors the reverse reaction.",
        "d) Speeds up the attainment of equilibrium.",
      ],
      correctAnswer: "d) Speeds up the attainment of equilibrium.",
    },
    {
      id: 16,
      question: "A chemical reaction is represented by the equation: A + B ⇌ C + D. This symbol (⇌) indicates that the reaction is:",
      answers: [
        "a) Irreversible and goes to completion.",
        "b) Reversible and can proceed in both directions.",
        "c) Exothermic and releases heat.",
        "d) Endothermic and absorbs heat.",
      ],
      correctAnswer: "b) Reversible and can proceed in both directions.",
    },
    {
      id: 17,
      question: "A closed container holds a reversible reaction at equilibrium. What will happen to the rate of the forward and reverse reactions if the pressure is increased (assuming the reaction produces more gas molecules on the product side)?",
      answers: [
        "a) The rate of the forward reaction will increase.",
        "b) The rate of the reverse reaction will increase.",
        "c) Both rates will decrease.",
        "d) Both rates will become equal.",
      ],
      correctAnswer: "b) The rate of the reverse reaction will increase.",
    },
  ],
};