import React from "react";

const questions = [
    "1 Explain the difference between a customer and a supplier.",
    "2 What is a cash transaction?",
    "3 What is a credit transaction?",
    "4 Give examples of purchases and expenses.",
    "5 When would petty cash be used?",
    "6 Name three payments made by the payroll department.",
    "7 Give two reasons why a business keeps a record of business transactions.",
    "8 Senior personnel should authorise major expenditure in a business. Why?",
    "9 Give one reason for maintaining a system of internal checks or controls.",
    "10 Why is it important for a business to pay expenses, such as wages, on time?",
];

const examQuestions = [
    {
        question:
            "1 A business buys goods on credit. When will this require the accounting records to be updated?",
        options: [
            "A Only when the goods are received",
            "B Only when the goods are paid for",
            "C When the goods are received and again when they are paid for",
            "D When the goods are received, again when they are paid for and when the goods are resold",
        ],
    },
    {
        question:
            "2 Which of the following describes the receipts generated by an Internet Service Provider?",
        options: [
            "A Income from sale of goods",
            "B Income from giving a service",
            "C Payments for employees",
            "D Payments for share capital",
        ],
    },
    {
        question: "3 How would you describe petty cash?",
        options: [
            "A Cash for some small everyday expenses",
            "B An overdraft arranged by the bank",
            "C Spare cash invested in a separate bank account",
            "D Money in the current account",
        ],
    },
    {
        question:
            "4 A stationery business sold computer supplies to a customer for payment in one month Which of the following are true in respect of this transaction?",
        options: [
            "(i) It is a cash transaction",
            "(ii) The expenditure must be authorised by the stationery business",
            "(iii) A record of the transaction must be kept in case of future query by the stationery business",
            "(iv) The stationery business will need to ensure that it receives payment in one month",
            "A (i) only",
            "B (ii) and (iii)",
            "C (iii) and (iv)",
            "D All of the above",
        ],
    },
    {
        question: "5 Which section of a grocery business pays salaries?",
        options: [
            "A Accounts department",
            "B Payroll",
            "C Sales",
            "D Store manager",
        ],
    },
];

export default function Page() {
    return (
        <div className="max-w-3xl mx-auto p-6">
            <h1 className="text-2xl font-bold mb-4">SELF TEST QUESTIONS</h1>
            <div className="mb-8">
                <p className="mb-2">Paragraph</p>
                <div className="flex gap-2 mb-4">
                    <span>1</span>
                    <span>3</span>
                    <span>3</span>
                    <span>3</span>
                    <span>4</span>
                    <span>5</span>
                    <span>6</span>
                    <span>7</span>
                    <span>8</span>
                    <span>9</span>
                    <span>9</span>
                </div>
                <ul className="list-decimal list-inside space-y-2">
                    {questions.map((q, i) => (
                        <li key={i}>{q}</li>
                    ))}
                </ul>
            </div>
            <h2 className="text-xl font-semibold mb-4">EXAM-STYLE QUESTIONS</h2>
            <div className="space-y-6">
                {examQuestions.map((q, i) => (
                    <div key={i}>
                        <p className="font-medium">{q.question}</p>
                        <ul className="list-none pl-4 space-y-1">
                            {q.options.map((opt, j) => (
                                <li key={j}>{opt}</li>
                            ))}
                        </ul>
                    </div>
                ))}
            </div>
            <p className="mt-8 text-sm text-gray-600">
                For suggested answers, see the Answers section at the end of the book.
            </p>
        </div>
    );
}