export const quiz = {
  questions: [
    {
      id: 1,
      question: "What is the SI unit of energy?",
      answers: ["Joule (J)", "Newton (N)", "Watt (W)", "Pascal (Pa)"],
      correctAnswer: "Joule (J)",
    },
    {
      id: 2,
      question: "What is the acceleration due to gravity on Earth?",
      answers: ["9.8 m/s²", "1.6 m/s²", "3.8 m/s²", "12.5 m/s²"],
      correctAnswer: "9.8 m/s²",
    },
    {
      id: 3,
      question: "Which of the following is a scalar quantity?",
      answers: ["Velocity", "Force", "Temperature", "Momentum"],
      correctAnswer: "Temperature",
    },
    {
      id: 4,
      question: "What is the SI unit of force?",
      answers: ["Newton (N)", "Kilogram (kg)", "Meter (m)", "Second (s)"],
      correctAnswer: "Newton (N)",
    },
    {
      id: 5,
      question: "Which of Newton&apos;slaws of motion describes the relationship between force, mass, and acceleration?",
      answers: ["First law", "Second law", "Third law", "None of the above"],
      correctAnswer: "Second law",
    },
    {
      id: 6,
      question: "What does the law of conservation of momentum state?",
      answers: [
        "Momentum is always zero",
        "Momentum is conserved in all interactions",
        "Momentum changes in every interaction",
        "Momentum is conserved only in elastic collisions",
      ],
      correctAnswer: "Momentum is conserved in all interactions",
    },
    {
      id: 7,
      question: "What is the SI unit of power?",
      answers: ["Watt (W)", "Joule (J)", "Newton (N)", "Pascal (Pa)"],
      correctAnswer: "Watt (W)",
    },
    {
      id: 8,
      question: "What is the speed of light in a vacuum?",
      answers: [
        "3 x 10^8 m/s",
        "3 x 10^6 m/s",
        "3 x 10^5 m/s",
        "3 x 10^7 m/s",
      ],
      correctAnswer: "3 x 10^8 m/s",
    },
    {
      id: 9,
      question: "Which force is responsible for keeping planets in orbit around the sun?",
      answers: ["Gravitational force", "Electromagnetic force", "Nuclear force", "Frictional force"],
      correctAnswer: "Gravitational force",
    },
    {
      id: 10,
      question: "Which of the following is a unit of work?",
      answers: ["Joule", "Watt", "Newton", "Meter"],
      correctAnswer: "Joule",
    },
    {
      id: 11,
      question: "What is the formula for kinetic energy?",
      answers: ["1/2 mv^2", "mv", "mgh", "1/2 kx^2"],
      correctAnswer: "1/2 mv^2",
    },
    {
      id: 12,
      question: "What does Hooke&apos;sLaw describe?",
      answers: ["Force is proportional to extension", "Force is proportional to velocity", "Force is proportional to area", "Force is proportional to mass"],
      correctAnswer: "Force is proportional to extension",
    },
    {
      id: 13,
      question: "Which of the following quantities is conserved in an elastic collision?",
      answers: ["Momentum and kinetic energy", "Momentum only", "Kinetic energy only", "Force"],
      correctAnswer: "Momentum and kinetic energy",
    },
    {
      id: 14,
      question: "What is the SI unit of electric current?",
      answers: ["Ampere (A)", "Volt (V)", "Watt (W)", "Ohm (Ω)"],
      correctAnswer: "Ampere (A)",
    },
    {
      id: 15,
      question: "Which phenomenon explains why objects float in water?",
      answers: ["Buoyancy", "Gravity", "Surface tension", "Viscosity"],
      correctAnswer: "Buoyancy",
    },
    {
      id: 16,
      question: "What is the first law of thermodynamics?",
      answers: [
        "Energy cannot be created or destroyed",
        "Entropy of a system never decreases",
        "Pressure is proportional to temperature",
        "The total momentum of a system is constant",
      ],
      correctAnswer: "Energy cannot be created or destroyed",
    },
    {
      id: 17,
      question: "Which of the following is a vector quantity?",
      answers: ["Velocity", "Temperature", "Mass", "Energy"],
      correctAnswer: "Velocity",
    },
    {
      id: 18,
      question: "What is the unit of frequency?",
      answers: ["Hertz (Hz)", "Meter (m)", "Second (s)", "Joule (J)"],
      correctAnswer: "Hertz (Hz)",
    },
    {
      id: 19,
      question: "What is the value of acceleration due to gravity on the Moon?",
      answers: ["1.6 m/s²", "9.8 m/s²", "3.8 m/s²", "12.5 m/s²"],
      correctAnswer: "1.6 m/s²",
    },
    {
      id: 20,
      question: "Which principle explains why an airplane can fly?",
      answers: ["Bernoulli&apos;sprinciple", "Archimedes' principle", "Pascal&apos;slaw", "Newton&apos;sthird law"],
      correctAnswer: "Bernoulli&apos;sprinciple",
    },
    {
      id: 21,
      question: "What is the equation for Ohm&apos;sLaw?",
      answers: ["V = IR", "P = IV", "E = mc^2", "F = ma"],
      correctAnswer: "V = IR",
    },
    {
      id: 22,
      question: "What is the primary cause of tides on Earth?",
      answers: ["The gravitational pull of the moon", "The gravitational pull of the sun", "Wind patterns", "Earth&apos;srotation"],
      correctAnswer: "The gravitational pull of the moon",
    },
    {
      id: 23,
      question: "Which of the following is a unit of pressure?",
      answers: ["Pascal (Pa)", "Joule (J)", "Watt (W)", "Meter (m)"],
      correctAnswer: "Pascal (Pa)",
    },
    {
      id: 24,
      question: "What does the Heisenberg Uncertainty Principle state?",
      answers: ["It is impossible to simultaneously know the exact position and momentum of a particle", "Energy levels of electrons are quantized", "Light behaves as both a wave and a particle", "Every action has an equal and opposite reaction"],
      correctAnswer: "It is impossible to simultaneously know the exact position and momentum of a particle",
    },
    {
      id: 25,
      question: "Which of the following best describes inertia?",
      answers: ["The tendency of an object to resist a change in motion", "The force of attraction between two objects", "The energy possessed by an object due to its motion", "The pressure exerted by a fluid"],
      correctAnswer: "The tendency of an object to resist a change in motion",
    },
    {
      id: 26,
      question: "Which of the following is the strongest fundamental force?",
      answers: ["Strong nuclear force", "Electromagnetic force", "Weak nuclear force", "Gravitational force"],
      correctAnswer: "Strong nuclear force",
    },
    {
      id: 27,
      question: "Which law explains the motion of planets around the sun?",
      answers: ["Kepler&apos;slaws of planetary motion", "Newton&apos;sfirst law", "Einstein&apos;stheory of relativity", "Faraday&apos;slaw"],
      correctAnswer: "Kepler&apos;slaws of planetary motion",
    },
    {
      id: 28,
      question: "What is the unit of capacitance?",
      answers: ["Farad (F)", "Henry (H)", "Ohm (Ω)", "Tesla (T)"],
      correctAnswer: "Farad (F)",
    },
    {
      id: 29,
      question: "What does the Doppler Effect describe?",
      answers: ["The change in frequency of a wave in relation to an observer", "The bending of light as it passes through a prism", "The conversion of mass to energy", "The reflection of light off a surface"],
      correctAnswer: "The change in frequency of a wave in relation to an observer",
    },
    {
      id: 30,
      question: "What is the unit of magnetic flux?",
      answers: ["Weber (Wb)", "Tesla (T)", "Volt (V)", "Henry (H)"],
      correctAnswer: "Weber (Wb)",
    },
    {
      id: 31,
      question: "What is the principle behind a lever?",
      answers: ["Mechanical advantage", "Conservation of energy", "Inertia", "Electromagnetic induction"],
      correctAnswer: "Mechanical advantage",
    },
    {
      id: 32,
      question: "What is the angle between two vectors if their dot product is zero?",
      answers: ["90 degrees", "0 degrees", "45 degrees", "180 degrees"],
      correctAnswer: "90 degrees",
    },
    {
      id: 33,
      question: "What is the value of the speed of sound in air at room temperature?",
      answers: ["343 m/s", "299,792,458 m/s", "9.8 m/s²", "1,000 m/s"],
      correctAnswer: "343 m/s",
    },
    {
      id: 34,
      question: "Which of the following is a non-renewable energy source?",
      answers: ["Coal", "Solar", "Wind", "Geothermal"],
      correctAnswer: "Coal",
    },
    {
      id: 35,
      question: "Which type of electromagnetic radiation has the shortest wavelength?",
      answers: ["Gamma rays", "X-rays", "Ultraviolet", "Radio waves"],
      correctAnswer: "Gamma rays",
    },
    {
      id: 36,
      question: "What does Coulomb&apos;sLaw describe?",
      answers: ["The force between two charged particles", "The behavior of light", "The speed of sound", "The pressure in fluids"],
      correctAnswer: "The force between two charged particles",
    },
    {
      id: 37,
      question: "What is the work-energy theorem?",
      answers: ["Work done is equal to the change in kinetic energy", "Energy cannot be created or destroyed", "The total energy in a system is conserved", "Momentum is conserved in all interactions"],
      correctAnswer: "Work done is equal to the change in kinetic energy",
    },
    {
      id: 38,
      question: "What is the unit of inductance?",
      answers: ["Henry (H)", "Farad (F)", "Ohm (Ω)", "Tesla (T)"],
      correctAnswer: "Henry (H)",
    },
    {
      id: 39,
      question: "Which of the following best describes entropy?",
      answers: ["A measure of disorder or randomness in a system", "The energy of motion", "The force between two objects", "The tendency of an object to resist changes in its state of motion"],
      correctAnswer: "A measure of disorder or randomness in a system",
    },
    {
      id: 40,
      question: "What is the SI unit of frequency?",
      answers: ["Hertz (Hz)", "Meter (m)", "Second (s)", "Joule (J)"],
      correctAnswer: "Hertz (Hz)",
    },
    {
      id: 41,
      question: "Which phenomenon explains the bending of light as it passes through a medium?",
      answers: ["Refraction", "Reflection", "Diffraction", "Interference"],
      correctAnswer: "Refraction",
    },
    {
      id: 42,
      question: "What is the relationship between wavelength and frequency?",
      answers: ["They are inversely proportional", "They are directly proportional", "They are unrelated", "They are equal"],
      correctAnswer: "They are inversely proportional",
    },
    {
      id: 43,
      question: "Which of the following is a unit of electric resistance?",
      answers: ["Ohm (Ω)", "Volt (V)", "Ampere (A)", "Farad (F)"],
      correctAnswer: "Ohm (Ω)",
    },
    {
      id: 44,
      question: "Which of the following laws describes the behavior of an ideal gas?",
      answers: ["Boyle&apos;sLaw", "Faraday&apos;sLaw", "Ohm&apos;sLaw", "Newton&apos;sFirst Law"],
      correctAnswer: "Boyle&apos;sLaw",
    },
    {
      id: 45,
      question: "What is the main factor that determines the speed of a wave?",
      answers: ["The medium through which it travels", "The amplitude of the wave", "The frequency of the wave", "The wavelength of the wave"],
      correctAnswer: "The medium through which it travels",
    },
  ],
};
