export const quiz = {
  totalQuestions: 45,
  questions: [
    {
      id: 1,
      question: "What is the SI unit of force?",
      answers: ["Newton (N)", "Kilogram (kg)", "Meter (m)", "Second (s)"],
      correctAnswer: "Newton (N)",
    },
    {
      id: 2,
      question: "Which of Newton&apos;slaws of motion describes the relationship between force, mass, and acceleration?",
      answers: ["First law", "Second law", "Third law", "None of the above"],
      correctAnswer: "Second law",
    },
    {
      id: 3,
      question: "The center of mass of a rigid body is:",
      answers: ["The point where the entire mass is concentrated", "The point where the body balances perfectly", "The point where the gravitational force is maximum", "The geometric center of the body"],
      correctAnswer: "The point where the entire mass is concentrated",
    },
    {
      id: 4,
      question: "If the line of action of a force passes through the center of mass, it will:",
      answers: ["Produce rotation", "Not produce any rotation", "Always cause the object to move", "Increase the object&apos;sweight"],
      correctAnswer: "Not produce any rotation",
    },
    {
      id: 5,
      question: "The center of gravity (CG) of an object is:",
      answers: ["The point where the mass is concentrated", "The point where the entire weight acts", "The point where the object balances", "The geometric center of the object"],
      correctAnswer: "The point where the entire weight acts",
    },
    {
      id: 6,
      question: "For tall objects, the center of mass and center of gravity:",
      answers: ["Are the same", "Are different due to altitude", "Cannot be determined", "Always coincide"],
      correctAnswer: "Are different due to altitude",
    },
    {
      id: 7,
      question: "The CM/CG of a homogeneous cube is at:",
      answers: ["Its geometric center", "The center of one face", "The edge midpoint", "Any corner"],
      correctAnswer: "Its geometric center",
    },
    {
      id: 8,
      question: "Which of the following objects has its CM/CG on the axis of symmetry?",
      answers: ["Homogeneous sphere", "Uniform wooden rod", "Right circular cylinder", "Irregular object"],
      correctAnswer: "Right circular cylinder",
    },
    {
      id: 9,
      question: "For a uniform wooden rod, the CM/CG is at:",
      answers: ["One end", "The midpoint", "One-third from the end", "Two-thirds from the end"],
      correctAnswer: "The midpoint",
    },
    {
      id: 10,
      question: "To determine the CG of an irregular object, you should:",
      answers: ["Measure its weight", "Use a plumb line and hang it from different points", "Calculate its volume", "Find its geometric center"],
      correctAnswer: "Use a plumb line and hang it from different points",
    },
    {
      id: 11,
      question: "What is the torque produced when a force of 50 N is applied at a perpendicular distance of 2 meters from the axis of rotation?",
      answers: ["100 Nm", "25 Nm", "50 Nm", "75 Nm"],
      correctAnswer: "100 Nm",
    },
    {
      id: 12,
      question: "Which of Newton&apos;slaws states that for every action, there is an equal and opposite reaction?",
      answers: ["First law", "Second law", "Third law", "Law of universal gravitation"],
      correctAnswer: "Third law",
    },
    {
      id: 13,
      question: "The moment of force (torque) is mathematically defined as:",
      answers: ["Force divided by distance", "Force times distance", "Distance divided by force", "Force minus distance"],
      correctAnswer: "Force times distance",
    },
    {
      id: 14,
      question: "Which of the following is not a type of rotational motion axis?",
      answers: ["Pivot", "Hinge", "Fulcrum", "Lever"],
      correctAnswer: "Lever",
    },
    {
      id: 15,
      question: "The moment of force that causes clockwise rotation is:",
      answers: ["Anticlockwise moment", "Positive moment", "Negative moment", "Zero moment"],
      correctAnswer: "Negative moment",
    },
    {
      id: 16,
      question: "The gravitational force acting on an object is directed towards:",
      answers: ["The center of mass", "The center of gravity", "The surface of the object", "The point of application of the force"],
      correctAnswer: "The center of gravity",
    },
    {
      id: 17,
      question: "For an object with a uniform density, where is the center of mass located?",
      answers: ["At the geometric center", "At the point of maximum density", "At the point of minimum density", "Randomly within the object"],
      correctAnswer: "At the geometric center",
    },
    {
      id: 18,
      question: "Which principle states that the mass of a system is equally distributed around its center of mass?",
      answers: ["Archimedes' Principle", "Bernoulli&apos;sPrinciple", "Newton&apos;sFirst Law", "Conservation of Momentum"],
      correctAnswer: "Conservation of Momentum",
    },
    {
      id: 19,
      question: "What happens to the center of mass of a rotating object when its shape changes?",
      answers: ["It remains unchanged", "It moves towards the denser part", "It moves towards the lighter part", "It always moves to the edge"],
      correctAnswer: "It remains unchanged",
    },
    {
      id: 20,
      question: "The point where an object can be balanced perfectly is called:",
      answers: ["Center of mass", "Center of gravity", "Center of rotation", "Geometric center"],
      correctAnswer: "Center of gravity",
    },
    {
      id: 21,
      question: "The moment of force is also known as:",
      answers: ["Gravitational force", "Torque", "Linear force", "Pressure"],
      correctAnswer: "Torque",
    },
    {
      id: 22,
      question: "For an object in equilibrium, the sum of all torques acting on it must be:",
      answers: ["Zero", "Equal to the weight of the object", "Equal to the mass of the object", "Equal to the gravitational force"],
      correctAnswer: "Zero",
    },
    {
      id: 23,
      question: "Which of the following statements about the center of mass is true for irregular objects?",
      answers: ["It is always at the geometric center", "It can be determined by balancing the object on a point", "It cannot be determined", "It is always at the bottom of the object"],
      correctAnswer: "It can be determined by balancing the object on a point",
    },
    {
      id: 24,
      question: "The center of mass of a uniform sphere is located:",
      answers: ["At the center of the sphere", "At the surface of the sphere", "At any point along the diameter", "Outside the sphere"],
      correctAnswer: "At the center of the sphere",
    },
    {
      id: 25,
      question: "In which of the following scenarios will the center of mass not lie at the geometric center?",
      answers: ["Uniform rod", "Homogeneous sphere", "Non-uniform rod", "Uniform cube"],
      correctAnswer: "Non-uniform rod",
    },
    {
      id: 26,
      question: "For an object to be in static equilibrium, which condition must be met?",
      answers: ["The center of mass must be at the geometric center", "The sum of all forces must be zero", "The object must be in motion", "The center of gravity must be at the highest point"],
      correctAnswer: "The sum of all forces must be zero",
    },
    {
      id: 27,
      question: "The torque due to a force is maximized when:",
      answers: ["The force is applied perpendicular to the moment arm", "The force is applied parallel to the moment arm", "The force is applied at the axis of rotation", "The moment arm is zero"],
      correctAnswer: "The force is applied perpendicular to the moment arm",
    },
    {
      id: 28,
      question: "Which of the following best describes the behavior of the center of mass in a freely falling object?",
      answers: ["It remains stationary", "It accelerates downward at the same rate as the object", "It moves upward", "It moves sideways"],
      correctAnswer: "It accelerates downward at the same rate as the object",
    },
    {
      id: 29,
      question: "The moment of force that causes anticlockwise rotation is:",
      answers: ["Positive moment", "Negative moment", "Zero moment", "Variable moment"],
      correctAnswer: "Positive moment",
    },
    {
      id: 30,
      question: "For an object suspended in equilibrium, the center of mass:",
      answers: ["Must be below the point of suspension", "Can be anywhere within the object", "Must be above the point of suspension", "Is irrelevant to equilibrium"],
      correctAnswer: "Must be below the point of suspension",
    },
    {
      id: 31,
      question: "The center of gravity of a tall building differs from the center of mass because:",
      answers: ["The building is not uniformly dense", "The gravitational field is not uniform at different heights", "The building has moving parts", "The center of gravity is always at the top"],
      correctAnswer: "The gravitational field is not uniform at different heights",
    },
    {
      id: 32,
      question: "Which method is commonly used to find the center of mass of a symmetrical object?",
      answers: ["Measuring its weight at different points", "Balancing it on a sharp edge", "Calculating its density at various points", "Using a geometric center formula"],
      correctAnswer: "Using a geometric center formula",
    },
    {
      id: 33,
      question: "The torque on an object is zero when:",
      answers: ["The force is applied at the center of mass", "The force is perpendicular to the moment arm", "The force is applied at the edge of the object", "The moment arm is maximized"],
      correctAnswer: "The force is applied at the center of mass",
    },
    {
      id: 34,
      question: "The center of mass of a system of particles is:",
      answers: ["The average position of all particles weighted by their masses", "The average position of all particles", "The point where the system’s mass is zero", "The midpoint of the system’s boundary"],
      correctAnswer: "The average position of all particles weighted by their masses",
    },
    {
      id: 35,
      question: "Which of the following is true about the center of gravity in a non-uniform gravitational field?",
      answers: ["It always lies at the geometric center of the object", "It is different from the center of mass", "It is the same as the center of mass", "It lies at the highest point of the object"],
      correctAnswer: "It is different from the center of mass",
    },
    {
      id: 36,
      question: "In an object with multiple connected parts, the overall center of mass is:",
      answers: ["The geometric center of the entire assembly", "The point where all parts are balanced", "The weighted average of the centers of mass of the individual parts", "The midpoint of the largest part"],
      correctAnswer: "The weighted average of the centers of mass of the individual parts",
    },
    {
      id: 37,
      question: "The principle of moments states that:",
      answers: ["The sum of clockwise moments equals the sum of anticlockwise moments for equilibrium", "The total mass is equally distributed", "The center of mass is at the geometric center", "The weight of the object determines its stability"],
      correctAnswer: "The sum of clockwise moments equals the sum of anticlockwise moments for equilibrium",
    },
    {
      id: 38,
      question: "Which of the following affects the center of gravity of an object?",
      answers: ["The object&apos;stemperature", "The object&apos;scolor", "The object&apos;sshape and mass distribution", "The object&apos;sage"],
      correctAnswer: "The object&apos;sshape and mass distribution",
    },
    {
      id: 39,
      question: "For a symmetrical object in a uniform gravitational field, the center of gravity is:",
      answers: ["Always at the same point as the center of mass", "Always at the top of the object", "Always at the bottom of the object", "Always outside the object"],
      correctAnswer: "Always at the same point as the center of mass",
    },
    {
      id: 40,
      question: "Which of the following is a condition for static equilibrium?",
      answers: ["The sum of all linear forces must be zero", "The sum of all forces and torques must be zero", "The center of mass must be at the bottom", "The object must be in motion"],
      correctAnswer: "The sum of all forces and torques must be zero",
    },
    {
      id: 41,
      question: "The point where the mass of an object seems to act is known as the:",
      answers: ["Center of gravity", "Center of mass", "Center of rotation", "Geometric center"],
      correctAnswer: "Center of gravity",
    },
    {
      id: 42,
      question: "In a rotating system, the torque depends on:",
      answers: ["The force applied and the distance from the axis of rotation", "The weight of the object and its density", "The speed of rotation and the mass", "The shape of the object"],
      correctAnswer: "The force applied and the distance from the axis of rotation",
    },
    {
      id: 43,
      question: "Which of the following best describes the center of mass in a system of multiple connected objects?",
      answers: ["The geometric center of the entire system", "The point where all objects balance", "The weighted average of the centers of mass of the objects", "The center of mass of the largest object"],
      correctAnswer: "The weighted average of the centers of mass of the objects",
    },
    {
      id: 44,
      question: "The torque is zero when the force is applied:",
      answers: ["At the center of mass", "Perpendicular to the moment arm", "Parallel to the moment arm", "At the edge of the object"],
      correctAnswer: "At the center of mass",
    },
    {
      id: 45,
      question: "The center of mass in a uniformly dense object is:",
      answers: ["At the geometric center", "At the point of maximum density", "At the point of minimum density", "Randomly within the object"],
      correctAnswer: "At the geometric center",
    },
  ],
};
