export const quiz = {
  totalQuestions: 20,
  questions: [
    {
      id: 1,
      question: "Number of periods in the periodic table are",
      answers: ["8", "7", "16", "5"],
      correctAnswer: "7",
    },
    {
      id: 2,
      question: "Which of the following groups contain alkaline earth metals?",
      answers: ["IA", "IIA", "VIIA", "VIIIA"],
      correctAnswer: "IIA",
    },
    {
      id: 3,
      question: "Which of the following elements belong to VIIIA?",
      answers: ["Na", "Mg", "Br", "Xe"],
      correctAnswer: "Xe",
    },
    {
      id: 4,
      question: "Main group elements are arranged in groups.",
      answers: ["6", "7", "8", "10"],
      correctAnswer: "8",
    },
    {
      id: 5,
      question: "Period number of Al is",
      answers: ["1", "2", "3", "4"],
      correctAnswer: "3",
    },
    {
      id: 6,
      question: "Valence shell electronic configuration of an element M (atomic no.14) is",
      answers: ["2s² 2p¹", "2s² 2p²", "2s² 2p³", "3s² 3p²"],
      correctAnswer: "3s² 3p²",
    },
    {
      id: 7,
      question: "Which of the following elements you expect to have greater shielding effect?",
      answers: ["Li", "Na", "K", "Rb"],
      correctAnswer: "Rb",
    },
    {
      id: 8,
      question: "As you move from right to left across a period, which of the following does not increase?",
      answers: ["Electron affinity", "Ionization energy", "Nuclear charge", "Shielding effect"],
      correctAnswer: "Shielding effect",
    },
    {
      id: 9,
      question: "All the elements of Group IIA are less reactive than alkali metals. This is because",
      answers: [
        "High ionization energies",
        "Relatively greater atomic sizes",
        "Similar electronic configuration",
        "Decreased nuclear charge",
      ],
      correctAnswer: "High ionization energies",
    },
    {
      id: 10,
      question: "Which of the following elements is an alkali metal?",
      answers: ["Calcium", "Sodium", "Chlorine", "Neon"],
      correctAnswer: "Sodium",
    },
    {
      id: 11,
      question: "The element with the electronic configuration [Ne] 3s² 3p⁵ belongs to which group in the periodic table?",
      answers: ["Group 1", "Group 2", "Group 17", "Group 18"],
      correctAnswer: "Group 17",
    },
    {
      id: 12,
      question: "Which of the following trends generally decreases down a group in the periodic table?",
      answers: ["Atomic radius", "Electron affinity", "Electronegativity", "Ionization energy"],
      correctAnswer: "Ionization energy",
    },
    {
      id: 13,
      question: "Which of the following elements is a transition metal?",
      answers: ["Boron", "Iron", "Argon", "Silicon"],
      correctAnswer: "Iron",
    },
    {
      id: 14,
      question: "The ion formed by an element in Group 2 of the periodic table will have a charge of",
      answers: ["+1", "+2", "-1", "-2"],
      correctAnswer: "+2",
    },
    {
      id: 15,
      question: "Which of the following properties is generally true for noble gases?",
      answers: [
        "High reactivity",
        "Low electron affinity",
        "High electronegativity",
        "High ionization energy",
      ],
      correctAnswer: "Low electron affinity",
    },
    {
      id: 16,
      question: "The element with the electronic configuration [Ar] 4s² 3d¹⁰ 4p⁴ is in which period of the periodic table?",
      answers: ["Period 3", "Period 4", "Period 5", "Period 6"],
      correctAnswer: "Period 4",
    },
    {
      id: 17,
      question: "Elements in the same group of the periodic table have similar chemical properties because they have the same:",
      answers: [
        "Atomic number",
        "Number of neutrons",
        "Number of atomic shells",
        "Number of valence electrons",
      ],
      correctAnswer: "Number of valence electrons",
    },
    {
      id: 18,
      question: "Which of the following elements is a halogen?",
      answers: ["Lithium", "Beryllium", "Bromine", "Krypton"],
      correctAnswer: "Bromine",
    },
    {
      id: 19,
      question: "The trend in atomic radius across a period in the periodic table is generally:",
      answers: ["Increasing", "Decreasing", "Constant", "Irregular"],
      correctAnswer: "Decreasing",
    },
    {
      id: 20,
      question: "Write the valence shell electronic configuration of an element present in the 3rd period and Group IIIA.",
      answers: ["1s² 2s² 2p⁶ 3s² 3p¹", "1s² 2s² 2p⁶ 3s²", "1s² 2s² 2p⁶", "1s² 2s² 2p⁶ 3s² 3p²"],
      correctAnswer: "1s² 2s² 2p⁶ 3s² 3p¹",
    },
  ],
};