export const quiz = {
  totalQuestions: 22,
  questions: [
    {
      id: 1,
      question: "What is the formula mass of CuSO₄·5H₂O? (Atomic masses: Cu = 63.5, S = 32, O = 16, H = 1)",
      answers: ["159.5", "185.5", "249.5", "149.5"],
      correctAnswer: "249.5",
    },
    {
      id: 2,
      question: "A compound with chemical formula Na₂CX₃ has formula mass 106 amu. Atomic mass of the element X is",
      answers: ["106", "23", "12", "16"],
      correctAnswer: "16",
    },
    {
      id: 3,
      question: "How many moles of molecules are there in 16g oxygen?",
      answers: ["1", "0.5", "0.1", "0.05"],
      correctAnswer: "0.5",
    },
    {
      id: 4,
      question: "What is the mass of 4 moles of hydrogen gas?",
      answers: ["8.064g", "4.032g", "1g", "1.008g"],
      correctAnswer: "8.064g",
    },
    {
      id: 5,
      question: "What is the mass of carbon present in 44g of carbon dioxide?",
      answers: ["12g", "6g", "24g", "44g"],
      correctAnswer: "12g",
    },
    {
      id: 6,
      question: "Which term is the same for one mole of oxygen and one mole of water?",
      answers: ["Volume", "Mass", "Atoms", "Molecules"],
      correctAnswer: "Molecules",
    },
    {
      id: 7,
      question: "If one mole of carbon contains x atoms, what is the number of atoms contained in 12g of Mg?",
      answers: ["x", "0.5x", "2x", "1.5x"],
      correctAnswer: "x",
    },
    {
      id: 8,
      question: "What is the molecular formula of a compound containing one carbon atom, two chlorine atoms, and three oxygen atoms?",
      answers: ["CCl₂O₃", "COCl₂", "C₂H₆O", "CClO"],
      correctAnswer: "CCl₂O₃",
    },
    {
      id: 9,
      question: "Given the ions Na⁺ and SO₄²⁻, what is the formula of the resulting ionic compound?",
      answers: ["NaSO₄", "Na₂SO₄", "Na₄SO₄", "Na₃SO₄"],
      correctAnswer: "Na₂SO₄",
    },
    {
      id: 10,
      question: "What is the molecular formula of a compound?",
      answers: [
        "The simplest whole number ratio of atoms in a molecule.",
        "The number and type of different atoms in one molecule.",
        "The number of moles in one molecule.",
        "The ratio of molar masses in a molecule.",
      ],
      correctAnswer: "The number and type of different atoms in one molecule.",
    },
    {
      id: 11,
      question: "When deducing the formula of a binary ionic compound, what information is crucial?",
      answers: [
        "Empirical formula",
        "Molecular structure",
        "Ions and relevant information",
        "Molar mass of the compound.",
      ],
      correctAnswer: "Ions and relevant information",
    },
    {
      id: 12,
      question: "How can you deduce the formula of a molecular substance from its given molecular structure?",
      answers: [
        "By analyzing its empirical formula",
        "By examining the molar mass",
        "By identifying the type of bonding",
        "By understanding the arrangement of atoms in the molecule.",
      ],
      correctAnswer: "By understanding the arrangement of atoms in the molecule.",
    },
    {
      id: 13,
      question: "Which relationship is represented by the equation amount of substance = mass / molar mass?",
      answers: ["Avogadro's number", "Ideal gas law", "Boyle's law", "Mole concept"],
      correctAnswer: "Mole concept",
    },
    {
      id: 14,
      question: "Define a mole as:",
      answers: [
        "The mass of one atom",
        "The amount of substance containing Avogadro's number of particles",
        "The number of particles in one molecule.",
        "The molar mass of a compound",
      ],
      correctAnswer: "The amount of substance containing Avogadro's number of particles",
    },
    {
      id: 15,
      question: "Explain the relationship between a mole and Avogadro's constant.",
      answers: [
        "A mole is defined as Avogadro's constant multiplied by the molar mass.",
        "A mole is equivalent to Avogadro's constant number of particles.",
        "Avogadro's constant is the sum of moles and particles",
        "Avogadro's constant represents the ratio of atoms to molecules.",
      ],
      correctAnswer: "A mole is equivalent to Avogadro's constant number of particles.",
    },
    {
      id: 16,
      question: "Deduce the symbol equation with state symbols for a chemical reaction given information. Which information is crucial for this deduction?",
      answers: [
        "Empirical formula",
        "Molar mass of the reactants",
        "Ions and state symbols",
        "Molecular structure of products",
      ],
      correctAnswer: "Ions and state symbols",
    },
    {
      id: 17,
      question: "Which of the following statements is incorrect about the mole concept?",
      answers: [
        "1 mole of any substance contains 6.02 × 10²³ particles.",
        "The molar mass of a substance is expressed in g/mol.",
        "The molar mass of a substance is the mass of 1 mole of that substance.",
        "The molar mass of a substance is the mass of 1 atom of that substance.",
      ],
      correctAnswer: "The molar mass of a substance is the mass of 1 atom of that substance.",
    },
    {
      id: 18,
      question: "Consider the reaction between magnesium and oxygen to form magnesium oxide. If 0.25 moles of magnesium react, what mass of magnesium oxide is produced?",
      answers: ["10g", "20g", "30g", "40g"],
      correctAnswer: "20g",
    },
  ],
};