export const quiz = {
  totalQuestions: 30,
  questions: [
    {
      id: 1,
      question: "What does 'SI' stand for in the context of units?",
      answers: [
        "System of International Units",
        "Système International d'Unités",
        "Standard International Units",
        "Scientific International Units",
      ],
      correctAnswer: "Système International d'Unités",
    },
    {
      id: 2,
      question: "Which of the following is the SI base unit for length?",
      answers: ["Meter", "Kilogram", "Second", "Ampere"],
      correctAnswer: "Meter",
    },
    {
      id: 3,
      question: "What is the SI base unit for mass?",
      answers: ["Gram", "Meter", "Kilogram", "Second"],
      correctAnswer: "Kilogram",
    },
    {
      id: 4,
      question: "What SI unit is used to measure time?",
      answers: ["Meter", "Second", "Ampere", "Kelvin"],
      correctAnswer: "Second",
    },
    {
      id: 5,
      question: "Which unit measures electric current in the SI system?",
      answers: ["Volt", "Ampere", "Ohm", "Watt"],
      correctAnswer: "Ampere",
    },
    {
      id: 6,
      question: "What is the SI base unit for temperature?",
      answers: ["Celsius", "Kelvin", "Fahrenheit", "Joule"],
      correctAnswer: "Kelvin",
    },
    {
      id: 7,
      question: "The amount of substance is measured in which SI unit?",
      answers: ["Mole", "Meter", "Liter", "Gram"],
      correctAnswer: "Mole",
    },
    {
      id: 8,
      question: "Which SI unit measures light intensity?",
      answers: ["Lux", "Watt", "Candela", "Newton"],
      correctAnswer: "Candela",
    },
    {
      id: 9,
      question: "What is the derived SI unit for area?",
      answers: ["Cubic meter", "Square meter", "Meter per second", "Newton"],
      correctAnswer: "Square meter",
    },
    {
      id: 10,
      question: "How is volume measured in SI units?",
      answers: ["Square meter", "Cubic meter", "Meter per second", "Joule"],
      correctAnswer: "Cubic meter",
    },
    {
      id: 11,
      question: "What is the SI derived unit for speed or velocity?",
      answers: ["Meter per second", "Newton", "Pascal", "Joule"],
      correctAnswer: "Meter per second",
    },
    {
      id: 12,
      question:
        "Which of the following is the SI derived unit for acceleration?",
      answers: [
        "Meter per second",
        "Meter per second squared",
        "Kilogram per cubic meter",
        "Newton",
      ],
      correctAnswer: "Meter per second squared",
    },
    {
      id: 13,
      question: "What is the SI derived unit for density?",
      answers: ["Kilogram per cubic meter", "Newton", "Pascal", "Joule"],
      correctAnswer: "Kilogram per cubic meter",
    },
    {
      id: 14,
      question: "What is the SI unit for force?",
      answers: ["Pascal", "Newton", "Joule", "Watt"],
      correctAnswer: "Newton",
    },
    {
      id: 15,
      question: "Which unit is used to measure pressure in the SI system?",
      answers: ["Newton", "Pascal", "Joule", "Ampere"],
      correctAnswer: "Pascal",
    },
    {
      id: 16,
      question: "The SI unit for energy is:",
      answers: ["Joule", "Newton", "Pascal", "Watt"],
      correctAnswer: "Joule",
    },
    {
      id: 17,
      question: "What is the derived SI unit for force?",
      answers: ["Kilogram per meter", "Newton", "Joule", "Pascal"],
      correctAnswer: "Newton",
    },
    {
      id: 18,
      question: "Which of the following is a base SI unit?",
      answers: ["Newton", "Kilogram", "Joule", "Pascal"],
      correctAnswer: "Kilogram",
    },
    {
      id: 19,
      question:
        "What unit is used to measure electric charge in the SI system?",
      answers: ["Ampere", "Coulomb", "Volt", "Ohm"],
      correctAnswer: "Coulomb",
    },
    {
      id: 20,
      question: "What is the unit for measuring luminous intensity?",
      answers: ["Watt", "Lux", "Candela", "Volt"],
      correctAnswer: "Candela",
    },
    {
      id: 21,
      question: "How is energy expressed in SI units?",
      answers: ["Newton", "Joule", "Pascal", "Watt"],
      correctAnswer: "Joule",
    },
    {
      id: 22,
      question: "The unit 'm²' represents which derived quantity?",
      answers: ["Volume", "Area", "Speed", "Force"],
      correctAnswer: "Area",
    },
    {
      id: 23,
      question: "The unit 'kg·m/s²' represents which derived quantity?",
      answers: ["Energy", "Pressure", "Force", "Density"],
      correctAnswer: "Force",
    },
    {
      id: 24,
      question: "The SI unit for temperature is:",
      answers: ["Celsius", "Kelvin", "Fahrenheit", "Joule"],
      correctAnswer: "Kelvin",
    },
    {
      id: 25,
      question: "What is the derived SI unit for pressure?",
      answers: ["Pascal", "Newton", "Joule", "Watt"],
      correctAnswer: "Pascal",
    },
    {
      id: 26,
      question: "The unit 'm³' is used to measure:",
      answers: ["Length", "Area", "Volume", "Speed"],
      correctAnswer: "Volume",
    },
    {
      id: 27,
      question: "Which of the following units is derived from base SI units?",
      answers: ["Meter", "Kilogram", "Newton", "Second"],
      correctAnswer: "Newton",
    },
    {
      id: 28,
      question: "What is the SI unit for electric current?",
      answers: ["Volt", "Ampere", "Ohm", "Watt"],
      correctAnswer: "Ampere",
    },
    {
      id: 29,
      question: "Which unit measures the amount of substance in the SI system?",
      answers: ["Mole", "Gram", "Liter", "Newton"],
      correctAnswer: "Mole",
    },
    {
      id: 30,
      question: "What is the base unit for mass in the SI system?",
      answers: ["Gram", "Pound", "Kilogram", "Ounce"],
      correctAnswer: "Kilogram",
    },
  ],
};
