export const quiz = {
  totalQuestions: 17,
  questions: [
    {
      id: 1,
      question: "Anything that has mass and occupies space is called ",
      answers: ["(a) Liquid", "(c) Solid", "(b) Gas", "(d) Matter"],
      correctAnswer: "(d) Matter",
    },
    {
      id: 2,
      question: "Following are states of matter",
      answers: ["(a) Gas", "(b) Liquid", "(c) Solid", "(d) All of these"],
      correctAnswer: "(d) All of these",
    },
    {
      id: 3,
      question: "Macroscopic properties that can be visualized by ",
      answers: ["(a) the naked eye", "(c) electron microscope", "(b) microscope", "(d) telescope"],
      correctAnswer: "(a) the naked eye",
    },
    {
      id: 4,
      question: "Matter can be described by both its",
      answers: ["(a) physical properties and chemical properties", "(b) Physical Properties ", "(c) Chemical Properties", "(d) Colligative Properties"],
      correctAnswer: "(a) physical properties and chemical properties",
    },
    {
      id: 5,
      question: "A substance formed when two ore more different elements combine chemically.",
      answers: ["(a) atom", "(b) compound", "(c) element", "(d) solution"],
      correctAnswer: "(b) compound",
    },
    {
      id: 6,
      question: "in which state of matter do particles have the least compressibility?",
      answers: ["(a) Solid", "(b) Liquid", "(c) Gas", "(d) Plasma"],
      correctAnswer: "(a) Solid",
    },
    {
      id: 7,
      question: "Light is not considered as matter despite the fact that it can behave like a particle. The reason behind the fact is that light lacks",
      answers: ["(a) Frequency", "(c) Wavelength", "(b) Material particle", "(d) Velocity"],
      correctAnswer: "(b) Material particle",
    },
    {
      id: 8,
      question: "A sealed container holding a gas is heated. Which of the following changes is most likely to occur?",
      answers: ["(a) Decrease in pressure and volume ", "(b) Increase in volume and pressure ", "(c) Decrease in volume and increase in pressure", "(d) No change in volume or pressure"],
      correctAnswer: "(b) Increase in volume and pressure",
    },
    {
      id: 9,
      question: "A material exhibits fluidity like a liquid but can be oriented in specific directions like a solid. This behavior is most likely characteristic of ",
      answers: ["(a) Plasma", "(b) Bose-Einstein condensate", "(c) Liquid crystal ", "(d) Neutron star"],
      correctAnswer: "(c) Liquid crystal",
    },
    {
      id: 10,
      question: "A cold, saturated salt solution is heated. What is most likely to happen?",
      answers: ["(a) All salt dissolves, forming a supersaturated solution", "(b) More salt dissolves due to increased solubility", "(c) No change in the amount of dissolved salt.", "(d) Salt crystals precipitate due to decreased solubility."],
      correctAnswer: "(b) More salt dissolves due to increased solubility",
    },
    {
      id: 11,
      question: "vl. What happens when a solution becomes saturated?",
      answers: ["(a) More solute can dissolve", "(b) No more solute can dissolve", "(c) It becomes a colloid", "(d) It turns into a suspension"],
      correctAnswer: "(b) No more solute can dissolve",
    },
    {
      id: 12,
      question: "vii. Analyze the concept of an element. What distinguishes it from compounds and mixtures?",
      answers: ["(a) Consists of multiple types of atoms", "(b) Comprises different molecules", "(c) Composed of only one type of atom", "(d) Demonstrates variable properties,"],
      correctAnswer: "(c) Composed of only one type of atom",
    },
    {
      id: 13,
      question: "viii. Evaluate the nature of particles in a colloid. How do they differ from those in a solution?",
      answers: ["(a) Solids that settle over time", "(b) Molecules evenly dispersed in a solvent", "(c) Large particles suspended in a medium?", "(d) lons forming a homogeneous mixture."],
      correctAnswer: "(c) Large particles suspended in a medium?",
    },
    {
      id: 14,
      question: "ix. Which of the following pairs does not represent allotropes of the same element?",
      answers: ["(a) Diamond and graphite", "(b) Oxygen and ozone", "(c) Phosphorus and Sulphur", "(d) Fullerenes and buckminsterfullerene"],
      correctAnswer: "(c) Phosphorus and Sulphur",
    },
    {
      id: 15,
      question: "Diamond and graphite are allotropes of carbon, yet they exhibit vastly different properties. This difference is primarily due to",
      answers: ["(a) Their atomic number", "(b) The arrangement of their atoms", "(c) Their isotopic composition", "(d) The presence of impurities"],
      correctAnswer: "(b) The arrangement of their atoms",
    },
    {
      id: 16,
      question: "What is the primary characteristic distinguishing elements, compounds and mixtures?",
      answers: ["(a) Color", "(b) Composition", "(c) State of matter", "(d) Density"],
      correctAnswer: "(b) Composition",
    },
    {
      id: 17,
      question: "You are investigating the solubility of sugar in water. You add sugar to a cup of water until no more dissolves, forming a saturated solution. If you continue to heat the solution, what would you expect to observe?",
      answers: ["(a) The sugar will completely dissolve", "(b) The undissolved sugar will settle at the bottom.", "(c) The solution will turn cloudy", "(d) The water will evaporate"],
      correctAnswer: "(a) The sugar will completely dissolve",
    },
  ],
};
