export const quiz = {
  totalQuestions: 20,
  questions: [
    {
      id: 1,
      question: "Which of the following atoms will form an ion of charge -2?",
      answers: ["12", "14", "8", "10"],
      correctAnswer: "8",
    },
    {
      id: 2,
      question: "Which of the following atoms will not form cation or anion?",
      answers: ["(atomic No. 16)", "(Atomic No. 17)", "(atomic No. 18)", "(Atomic No. 19)"],
      correctAnswer: "(atomic No. 18)",
    },
    {
      id: 3,
      question: "Which of the following atoms will form cation?",
      answers: ["20", "18", "17", "15"],
      correctAnswer: "20",
    },
    {
      id: 4,
      question: "Which of the following atoms obey duplet rule?",
      answers: ["O2", "F2", "H2", "N2"],
      correctAnswer: "H2",
    },
    {
      id: 5,
      question: "Silicon belongs to Group IVA. It has electrons in the valence shell.",
      answers: ["2", "3", "4", "5"],
      correctAnswer: "4",
    },
    {
      id: 6,
      question: "Phosphorus belongs to third period of Group VA. How many electrons it needs to complete its valence shell?",
      answers: ["2", "3", "4", "5"],
      correctAnswer: "3",
    },
    {
      id: 7,
      question: "In the formation of AlF3, aluminum atom loses electrons.",
      answers: ["1", "2", "3", "4"],
      correctAnswer: "3",
    },
    {
      id: 8,
      question: "Which of the following is not true about the formation of Na2S?",
      answers: [
        "Each sodium atom loses one electron",
        "Sodium forms cation",
        "Sulphur forms anion",
        "Each Sulphur atom gains one electron",
      ],
      correctAnswer: "Each Sulphur atom gains one electron",
    },
    {
      id: 9,
      question: "Identify the covalent compound.",
      answers: ["NaCl", "MgO", "H₂O", "KF"],
      correctAnswer: "H₂O",
    },
    {
      id: 10,
      question: "Which statement is NOT true about Cation/anion formation?",
      answers: [
        "Metals lose, non-metals gain electrons",
        "Charge based on gained/lost electrons",
        "Stability influenced by valence shell.",
        "Lower energy state drives the process.",
      ],
      correctAnswer: "Stability influenced by valence shell.",
    },
    {
      id: 11,
      question: "Which of the following statement highlights the electropositive nature of metals?",
      answers: [
        "Form cation (ionic bonds)",
        "Share electrons covalently",
        "Gain electrons (anions)",
        "Strong polar covalent forces",
      ],
      correctAnswer: "Form cation (ionic bonds)",
    },
    {
      id: 12,
      question: "Pick out the correct relation between bonding type and properties.",
      answers: [
        "Ionic brittle due to strong forces",
        "Covalent high m.p./b.p. due to weak forces",
        "Metallic good conductors (heat & electricity)",
        "Coordinate covalent ionize in water due to strong forces",
      ],
      correctAnswer: "Metallic good conductors (heat & electricity)",
    },
    {
      id: 13,
      question: "Choose the incorrect statement about electrical conductivity.",
      answers: [
        "Ionic melts/solutions conduct due to ions",
        "Covalent molecule poor conductors in all states",
        "Some ionic solids conduct due to mobile ions.",
        "Metallic bonding allows conduction via delocalized electrons.",
      ],
      correctAnswer: "Some ionic solids conduct due to mobile ions.",
    },
    {
      id: 14,
      question: "Diamond and graphite both are solids made of carbon. However, there is huge difference between their melting and boiling points. Why? Pick up the correct reason.",
      answers: [
        "Covalent sharing requires more energy to break.",
        "Stronger electrostatic forces in NaCl",
        "Diamond's structure hinders movement, NaCl ions move freely.",
        "Size difference between ions and atoms.",
      ],
      correctAnswer: "Covalent sharing requires more energy to break.",
    },
    {
      id: 15,
      question: "Beside consisting of similar constituent element, their properties are different. Why?",
      answers: [
        "Graphite-strong covalent layers, diamond weak metallic bonds.",
        "Graphite-delocalized electrons (metallic) for conductivity.",
        "Diamond strong covalent network restricts movement (hardness).",
        "Graphite-weak van der Waals forces allows layers to slide",
      ],
      correctAnswer: "Diamond strong covalent network restricts movement (hardness).",
    },
    {
      id: 16,
      question: "Why are metals good conductors of electricity?",
      answers: [
        "Free movement of electrons due to metallic bonding.",
        "Strong ionic attractions hinder electron movement.",
        "Covalent bonds restrict electron and heat mobility.",
        "Weak van der Waals forces limit energy and charged particle transfer.",
      ],
      correctAnswer: "Free movement of electrons due to metallic bonding.",
    },
    {
      id: 17,
      question: "What is the main characteristic of metallic bonding?",
      answers: [
        "Sharing of electrons between non-metals",
        "Transfer of electrons from metals to non-metals",
        "Electrostatic attraction between a sea of delocalized electrons and positively charged cations.",
        "Strong intermolecular forces between neutral molecules",
      ],
      correctAnswer: "Electrostatic attraction between a sea of delocalized electrons and positively charged cations.",
    },
    {
      id: 18,
      question: "Which property allows metals to be drawn into wires?",
      answers: ["High melting point", "Low electrical conductivity", "Ductile", "Insolubility in water"],
      correctAnswer: "Ductile",
    },
    {
      id: 19,
      question: "What type of bond is formed when two atoms share one or more pairs of electrons?",
      answers: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
      correctAnswer: "Covalent bond",
    },
  ],
};