import React from 'react'

const page = () => {
    return (
        <div>
            <h2 className="text-xl font-semibold mb-2">13.3 STRUCTURAL FORMULA</h2>            <p className="mb-4">                Frequently more than one organic compounds are represented by the same molecular formula. However, they have different properties. They have different structural formulas. For example, ethanol and dimethyl ether have the same molecular formula C₂H₅O. But they have different structures.            </p>            <p className="mb-4">                In ethanol, the oxygen atom is bonded to a carbon atom and a hydrogen atom. Whereas in dimethyl ether, the oxygen atom is bonded to two carbon atoms.            </p>            <p className="mb-4">                Similarly, two organic compounds have the molecular formula C₃H₆O₃. They have different arrangement of atoms.            </p>            <p className="mb-4">                A formula that describes the arrangement of atoms in a molecule is called a structural formula.            </p>            <p className="mb-4">                The simple alkanes are straight-chain hydrocarbons. First three members of alkanes have following structural formulas.            </p>            <p className="mb-4">                Methane <br />                CH₄ <br />                Ethane <br />                C₂H₆ <br />                Propane <br />                C₃H₈            </p>            <p className="mb-4">                The condensed structural formulas of these alkanes are CH₄, CH₃CH₃, CH₃CH₂CH₃. The corresponding molecular formulas are C₁H₄, C₂H₆, C₃H₈ respectively.            </p>            <p className="mb-4">                A condensed formula is a structural formula that uses established abbreviation for various groups of chain. In condensed structural formula, we list the main chain carbon atoms and the hydrogen atoms attached to them in the sequence in which they appear in the naming system.            </p>
            <h3 className="text-lg font-semibold mb-2">Table 13.2: Properties of different states of matter</h3>            <table className="min-w-full border-collapse border border-gray-200 mb-4">                <thead>                    <tr>                        <th className="border border-gray-300 px-4 py-2">Name</th>                        <th className="border border-gray-300 px-4 py-2">Molecular Formula</th>                        <th className="border border-gray-300 px-4 py-2">Condensed Formula</th>                    </tr>                </thead>                <tbody>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Butane</td>                        <td className="border border-gray-300 px-4 py-2">C₄H₁₀</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Pentane</td>                        <td className="border border-gray-300 px-4 py-2">C₅H₁₂</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Hexane</td>                        <td className="border border-gray-300 px-4 py-2">C₆H₁₄</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Heptane</td>                        <td className="border border-gray-300 px-4 py-2">C₇H₁₆</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Octane</td>                        <td className="border border-gray-300 px-4 py-2">C₈H₁₈</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₂CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Nonane</td>                        <td className="border border-gray-300 px-4 py-2">C₉H₂₀</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₂CH₂CH₂CH₂CH₃</td>                    </tr>                    <tr>                        <td className="border border-gray-300 px-4 py-2">Decane</td>                        <td className="border border-gray-300 px-4 py-2">C₁₀H₂₂</td>                        <td className="border border-gray-300 px-4 py-2">CH₃CH₂CH₂CH₂CH₂CH₂CH₂CH₂CH₂CH₃</td>                    </tr>                </tbody>            </table>
            <h2 className="text-xl font-semibold mb-2">Example 13.1</h2>            <p className="mb-4">                Give the molecular formula, the structural formula and the condensed structural formula for pentane            </p>            <p className="mb-4">                Problem Solving Strategy            </p>            <ol className="list-decimal list-inside mb-4">                <li>The stem pent- means five carbon atoms.</li>                <li>The ending -ane indicates an alkane.</li>                <li>Write a string or chain of five carbon atoms.</li>                <li>For the condensed molecular formula, write each carbon atom&apos;s set of hydrogen atoms next to the carbon.</li>                <li>For molecular formula, simply count the carbon and hydrogen atoms or use the general formula CₙH₂ₙ₊₂ with n=5.</li>                <li>Attach hydrogen atoms to the carbons to give each carbon atom four bonds. This requires three hydrogen atoms on each end carbon and two each on others.</li>            </ol>            <p className="mb-4">                Solution:            </p>            <p className="mb-4">                Structural formula            </p>            <p className="mb-4">                H₃C-CH₂-CH₂-CH₂-CH₃ <br />                Condensed Structural formula <br />                C₅H₁₂            </p>            <p className="mb-4">                Molecular formula <br />                C₅H₁₂            </p>
            <h2 className="text-xl font-semibold mb-2">CONCEPT ASSESSMENT EXERCISE 13.2</h2>            <p className="mb-4">                Give the molecular, structural and condensed structural formulas for            </p>            <ol className="list-decimal list-inside mb-4">                <li>Butane</li>                <li>Hexane</li>                <li>Octane</li>            </ol>
        </div>
    )
}

export default page