export const quiz = {
  totalQuestions: 40,
  questions: [
      {
    id: 1,
    question: "What does CSS stand for?",
    answers: [
      "A) Cascading Style Sheets",
      "B) Computer Style Sheets",
      "C) Creative Style Sheets",
      "D) Colorful Style Sheets",
    ],
    correctAnswer: "A) Cascading Style Sheets",
  },
  {
    id: 2,
    question: "Which CSS type has the highest priority?",
    answers: [
      "A) Inline CSS",
      "B) Embedded (Internal) CSS",
      "C) External CSS",
      "D) Browser default CSS",
    ],
    correctAnswer: "A) Inline CSS",
  },
  {
    id: 3,
    question: "Which tag is used for embedding internal CSS?",
    answers: [
      "A) <link>",
      "B) <style>",
      "C) <script>",
      "D) <meta>",
    ],
    correctAnswer: "B) <style>",
  },
  {
    id: 4,
    question: "How do you link an external CSS file in HTML?",
    answers: [
      "A) <link rel='stylesheet' href='styles.css'>",
      "B) <style src='styles.css'>",
      "C) <stylesheet src='styles.css'>",
      "D) <css link='styles.css'>",
    ],
    correctAnswer: "A) <link rel='stylesheet' href='styles.css'>",
  },
  {
    id: 5,
    question: "Which property is used to change the background color of a table?",
    answers: [
      "A) table-background",
      "B) background-table",
      "C) background-color",
      "D) table-color",
    ],
    correctAnswer: "C) background-color",
  },
  {
    id: 6,
    question: "How do you create a border for a table in CSS?",
    answers: [
      "A) table, th, td { border: 1px solid black; }",
      "B) table { border: 1px solid black; }",
      "C) th, td { border: 1px solid black; }",
      "D) table { border-style: solid; border-width: 1px; }",
    ],
    correctAnswer: "A) table, th, td { border: 1px solid black; }",
  },
  {
    id: 7,
    question: "What is the purpose of the 'marquee' element?",
    answers: [
      "A) To create scrolling text",
      "B) To embed a video",
      "C) To link an external stylesheet",
      "D) To create a table",
    ],
    correctAnswer: "A) To create scrolling text",
  },
  {
    id: 8,
    question: "Which attribute is used to autoplay a video?",
    answers: [
      "A) controls",
      "B) loop",
      "C) autoplay",
      "D) muted",
    ],
    correctAnswer: "C) autoplay",
  },
  {
    id: 9,
    question: "How can you change the background color of the body?",
    answers: [
      "A) body { color: #E6E6FA; }",
      "B) body { background-color: #E6E6FA; }",
      "C) body { bg-color: #E6E6FA; }",
      "D) body { bg: #E6E6FA; }",
    ],
    correctAnswer: "B) body { background-color: #E6E6FA; }",
  },
  {
    id: 10,
    question: "What is the correct HTML tag for embedding a video?",
    answers: [
      "A) <media>",
      "B) <video>",
      "C) <movie>",
      "D) <clip>",
    ],
    correctAnswer: "B) <video>",
  },
  {
    id: 11,
    question: "Which tag is used to define a scrolling container in HTML?",
    answers: [
      "A) <scroll>",
      "B) <container>",
      "C) <marquee>",
      "D) <div>",
    ],
    correctAnswer: "C) <marquee>",
  },
  {
    id: 12,
    question: "How do you center-align text in CSS?",
    answers: [
      "A) text-center",
      "B) text-align: center",
      "C) align-center",
      "D) center-align",
    ],
    correctAnswer: "B) text-align: center",
  },
  {
    id: 13,
    question: "What CSS property is used to change the text color?",
    answers: [
      "A) font-color",
      "B) color",
      "C) text-color",
      "D) fg-color",
    ],
    correctAnswer: "B) color",
  },
  {
    id: 14,
    question: "Which tag is used to define a table in HTML?",
    answers: [
      "A) <tbl>",
      "B) <table>",
      "C) <td>",
      "D) <th>",
    ],
    correctAnswer: "B) <table>",
  },
  {
    id: 15,
    question: "What is the purpose of the <th> tag in HTML?",
    answers: [
      "A) To define a table header",
      "B) To define a table row",
      "C) To define a table cell",
      "D) To define a table footer",
    ],
    correctAnswer: "A) To define a table header",
  },
  {
    id: 16,
    question: "Which HTML attribute is used to specify an alternate text for an image, if the image cannot be displayed?",
    answers: [
      "A) alt",
      "B) title",
      "C) src",
      "D) description",
    ],
    correctAnswer: "A) alt",
  },
  {
    id: 17,
    question: "How do you add a comment in CSS?",
    answers: [
      "A) // this is a comment",
      "B) /* this is a comment */",
      "C) <!-- this is a comment -->",
      "D) # this is a comment",
    ],
    correctAnswer: "B) /* this is a comment */",
  },
  {
    id: 18,
    question: "What is the correct HTML for adding a background color?",
    answers: [
      "A) <background>yellow</background>",
      "B) <body bg='yellow'>",
      "C) <body style='background-color:yellow;'>",
      "D) <body bgcolor='yellow'>",
    ],
    correctAnswer: "C) <body style='background-color:yellow;'>",
  },
  {
    id: 19,
    question: "Which property is used to change the font of an element in CSS?",
    answers: [
      "A) font-family",
      "B) font-style",
      "C) font-weight",
      "D) font-size",
    ],
    correctAnswer: "A) font-family",
  },
  {
    id: 20,
    question: "What does the 'autoplay' attribute do in the <video> tag?",
    answers: [
      "A) It plays the video on a loop.",
      "B) It mutes the video by default.",
      "C) It starts playing the video automatically.",
      "D) It displays video controls.",
    ],
    correctAnswer: "C) It starts playing the video automatically.",
  },
  {
    id: 21,
    question: "Which HTML tag is used to define an internal style sheet?",
    answers: [
      "A) <css>",
      "B) <script>",
      "C) <style>",
      "D) <link>",
    ],
    correctAnswer: "C) <style>",
  },
  {
    id: 22,
    question: "Which CSS property is used to change the text color of an element?",
    answers: [
      "A) fgcolor",
      "B) color",
      "C) text-color",
      "D) font-color",
    ],
    correctAnswer: "B) color",
  },
  {
    id: 23,
    question: "How do you display a border like this: The top border = 10 pixels, the bottom border = 5 pixels, the left border = 20 pixels, and the right border = 1pixel?",
    answers: [
      "A) border-width:10px 1px 5px 20px;",
      "B) border-width:10px 20px 5px 1px;",
      "C) border-width:10px 5px 20px 1px;",
      "D) border-width:10px 1px 20px 5px;",
    ],
    correctAnswer: "A) border-width:10px 1px 5px 20px;",
  },
  {
    id: 24,
    question: "How do you make each word in a text start with a capital letter in CSS?",
    answers: [
      "A) text-transform:capitalize",
      "B) text-transform:uppercase",
      "C) text-transform:lowercase",
      "D) text-transform:capitalize-each",
    ],
    correctAnswer: "A) text-transform:capitalize",
  },
  {
    id: 25,
    question: "What is the default value of the position property in CSS?",
    answers: [
      "A) fixed",
      "B) absolute",
      "C) relative",
      "D) static",
    ],
    correctAnswer: "D) static",
  },
  {
    id: 26,
    question: "Which property is used to change the left margin of an element in CSS?",
    answers: [
      "A) padding-left",
      "B) margin-left",
      "C) indent",
      "D) spacing-left",
    ],
    correctAnswer: "B) margin-left",
  },
  {
    id: 27,
    question: "What is the use of the <h1> tag in HTML?",
    answers: [
      "A) To define the most important heading",
      "B) To define a paragraph",
      "C) To define a hyperlink",
      "D) To define an image",
    ],
    correctAnswer: "A) To define the most important heading",
  },
  {
    id: 28,
    question: "Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?",
    answers: [
      "A) alt",
      "B) title",
      "C) src",
      "D) href",
    ],
    correctAnswer: "A) alt",
  },
  {
    id: 29,
    question: "What is the purpose of the <p> tag in HTML?",
    answers: [
      "A) To define a paragraph",
      "B) To define a header",
      "C) To define a table",
      "D) To define a list",
    ],
    correctAnswer: "A) To define a paragraph",
  },
  {
    id: 30,
    question: "Which CSS property controls the text size?",
    answers: [
      "A) font-style",
      "B) text-size",
      "C) font-size",
      "D) text-style",
    ],
    correctAnswer: "C) font-size",
  },
  {
    id: 31,
    question: "Which HTML tag is used to define a hyperlink?",
    answers: [
      "A) <a>",
      "B) <link>",
      "C) <href>",
      "D) <hyperlink>",
    ],
    correctAnswer: "A) <a>",
  },
  {
    id: 32,
    question: "Which CSS property is used to change the background color?",
    answers: [
      "A) background-color",
      "B) color",
      "C) bg-color",
      "D) bg-color",
    ],
    correctAnswer: "A) background-color",
  },
  {
    id: 33,
    question: "What is the correct HTML for adding a background color?",
    answers: [
      "A) <background>yellow</background>",
      "B) <body bg='yellow'>",
      "C) <body style='background-color:yellow;'>",
      "D) <body bgcolor='yellow'>",
    ],
    correctAnswer: "C) <body style='background-color:yellow;'>",
  },
  {
    id: 34,
    question: "Which HTML attribute is used to define inline styles?",
    answers: [
      "A) class",
      "B) styles",
      "C) style",
      "D) font",
    ],
    correctAnswer: "C) style",
  },
  {
    id: 35,
    question: "Which HTML element is used to specify a footer for a document or section?",
    answers: [
      "A) <bottom>",
      "B) <section>",
      "C) <footer>",
      "D) <foot>",
    ],
    correctAnswer: "C) <footer>",
  },
  {
    id: 36,
    question: "Which CSS property is used to change the text color of an element?",
    answers: [
      "A) fgcolor",
      "B) color",
      "C) text-color",
      "D) font-color",
    ],
    correctAnswer: "B) color",
  },
  {
    id: 37,
    question: "How do you display hyperlinks without an underline in CSS?",
    answers: [
      "A) a {text-decoration:none;}",
      "B) a {decoration:no-underline;}",
      "C) a {underline:none;}",
      "D) a {text-decoration:no-underline;}",
    ],
    correctAnswer: "A) a {text-decoration:none;}",
  },
  {
    id: 38,
    question: "Which HTML element is used to define important text?",
    answers: [
      "A) <i>",
      "B) <strong>",
      "C) <important>",
      "D) <b>",
    ],
    correctAnswer: "B) <strong>",
  },
  {
    id: 39,
    question: "How do you make a list that lists its items with squares in CSS?",
    answers: [
      "A) list-style-type: square;",
      "B) list-type: square;",
      "C) list: square;",
      "D) list-style: square;",
    ],
    correctAnswer: "A) list-style-type: square;",
  },
  {
    id: 40,
    question: "How do you group selectors in CSS?",
    answers: [
      "A) Separate each selector with a space",
      "B) Separate each selector with a plus sign",
      "C) Separate each selector with a comma",
      "D) Separate each selector with a dot",
    ],
    correctAnswer: "C) Separate each selector with a comma",
  },
  ],
};
